name: Release Kibana Reports Artifacts

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Checkout Plugin
        uses: actions/checkout@v1
      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.9.1
          path: kibana-reports/kibana
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.22.0"
      - name: Move Kibana Reports to Plugins Dir
        run: |
          mkdir kibana/plugins
          mv kibana-reports kibana/plugins
      - name: Kibana Plugin Bootstrap
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: cd kibana/plugins/kibana-reports; yarn kbn bootstrap
      - name: Build Artifact
        run: |
          cd kibana/plugins/kibana-reports
          yarn build
          artifact=`ls ./build/*.zip`
          aws s3 cp $artifact s3://kiabna-reports/kibana-reports-plugin/
          # aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/downloads/*"
