name: Test and Build Reports Scheduler

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      - name: Build with Gradle
        run: |
          cd reports-scheduler
          ./gradlew build

      - name: Create Artifact Path
        run: |
          mkdir -p reports-scheduler-builds
          cp -r ./reports-scheduler/build/distributions/*.zip reports-scheduler-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: reports-scheduler
          path: reports-scheduler-builds
