name: Test and Build Kibana Reports

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.9.1
          path: kibana
      - name: Checkout Plugin
        uses: actions/checkout@v1
        with:
          path: kibana/plugins/opendistro_kibana_reports
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.22.0'
      - name: Kibana Pluign Bootstrap
        run: |
          yarn kbn bootstrap
      - name: Build Artifact
        run: |
          yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: opendistro_kibana_reports
          path: ./build
